version: "2"

networks:
  app:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app
  kafka:
    image: docker.io/bitnami/kafka:3.1
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - app
    links:
      - zookeeper
    depends_on:
      - zookeeper

  app-producer:
    build:
      context: ./app
    networks:
      - app
    command: "sleep 10 && /app/kafka-producer.py"
    links:
      - kafka
    depends_on:
      - kafka

  app-consumer:
    build:
      context: ./app
    networks:
      - app
    command: "sleep 10 && /app/kafka-consumer.py"
    links:
      - kafka
    depends_on:
      - kafka


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
